### ISSUE TITLE
Debian packages have moved

### ISSUE THREAD

**Issue by scottsweb** [bluet/docker-jottacloud#14]
https://docs.jottacloud.com/en/articles/1436855-jottacloud-cli-for-linux-debian-packages

Looks like the updated URL is `https://repo.jotta.cloud` but I am also seeing login errors with the service which I believe may be further changes on the Jottacloud side.

**Comment by bluet** [comment]
thanks @scottsweb , I'll work on this soon.

**Comment by bluet** [comment]
released 0.15.109709 https://hub.docker.com/r/bluet/jottacloud/tags
