### ISSUE TITLE
download rate and upload rate not working

### ISSUE THREAD

**Issue by olli1986** [bluet/docker-jottacloud#17]
Hello

I got it to work successfully, but download rate and upload rate not working.
It doesn't matter what I set, it always uploads at full power

Hardware:
Synology DS920+

**Comment by bluet** [comment]
Hi @olli1986 , how did you set the transfer rates?

**Comment by olli1986** [comment]
Hi bluet,
I set both to 1M to test.
I've also tried 1m.
According to the upstream from the FritzBox it goes to about 300Mbit/s

**Comment by bluet** [comment]
It doesn't support setting upload/download rates from environment variables. At least not yet. 😂

You have to start the docker container and use `docker exec -it jottacloud bash` to get the shell access inside the container, and then set the settings with jotta-cli.

Or, if you're willing to, you can add the features in entry point.sh! PRs welcome 🤗

**Comment by olli1986** [comment]
Now I understand. It works perfectly now.

I used the following line:
jotta-cli config set uploadrate 5m
