### ISSUE TITLE
Jotta-cli version

### ISSUE THREAD

**Issue by ckvist72** [bluet/docker-jottacloud#7]
A new version of Jotta Cli is available.
 Please update from 0.14.60923 to version 0.15.75295
 
 To update jotta-cli just download and install
 most recent build from
 https://repo.jotta.us/archives/linux/[ARCH]/
 or 
 use the packagemanger used to install jotta-cli

**Comment by bluet** [comment]
The updated version's 9n dockerhub now, thanks for letting me know!

**Comment by bluet** [comment]
Close for now, please don't hesitate to reply here if there's anything wrong with the new build, I'll reopen this issue :-)

**Comment by bluet** [comment]
Do you have all required ENV variables set?
I just updated the container running on my NAS with the latest image, and running fine.

Would you mind check again, and if the error persists, provide more information about your environment and how to reproduce it?

**Comment by ckvist72** [comment]
Yes. And it is also running fine here. But it seems like it tryes something, fails, and then try again and succed.

So many it does not matter, i just wanted to tell you.

⁣Hent BlueMail til Android ​

Den 24. feb. 2023 15.12, fra 15.12, "BlueT - Matthew Lien - 練喆明" ***@***.***> skrev:

**Comment by bluet** [comment]
@ckvist72 I see. Thanks for the information. I'll see what I can do. :-)
